ijry/uview-plus

src/uni_modules/uview-plus/components/u-parse/node/node.vue, src/uni_modules/uview-plus/components/u-parse/parser.js, src/uni_modules/uview-plus/components/u-parse/u-parse.vue
=> 修复富文本事件名称大小写问题

src/uni_modules/uview-plus/components/u-datetime-picker/u-datetime-picker.vue, src/uni_modules/uview-plus/components/u-picker/u-picker.vue
问题截图:
问题描述:
将时间划到设置的最小时间,在操作年份修改时,实际选中值和下拉列表显示选中值不一致.
这里应该是在显示最小时间数据时,其它列数据不够完整,在修改年份后,列数据在设置选中索引后才变化了,会导致其它列数据显示不对
这里的图中只有日这列数据显示不对,如果将最小时间月份设为9,会发现月份列的显示数据也不对
=> fix:修改u-datetime-picker组件有限制最大最小值时时间列表的显示数据和选中数据不一致问题

src/uni_modules/uview-plus/components/u-picker/u-picker.vue
修复在支付宝小程序上因为使用text标签，上面的类名使用的样式不生效，导致所有选择的项目显示到了一行的问题
=> 修复在支付宝小程序上因为使用text标签，上面的类名使用的样式不生效，导致所有选择的项目显示到了一行的问题

src/uni_modules/uview-plus/components/u-icon/u-icon.vue
> **背景**：使用过程中发现按照官网自定义图标的步骤配置后，页面中显示异常，排查后发现是因为没有加上自定义图标的字体样式导致的，所以对这一问题进行修复
预期表现
实际表现
代码
=> fix: 修复自定义图标无效问题

src/uni_modules/uview-plus/components/u-tabs/u-tabs.vue
修复tabs组件中，激活当前样式部分的bug
错误原因:：uin.$u.addStyle方法未定义。
解决：直接调用已引入的addStyle方法。
=> 修复tabs中，当前激活样式的undefined bug

src/uni_modules/uview-plus/types/comps/form.d.ts
按照文档描述，第二个参数是可选。
源码中也有实现相应的判断
https://github.com/ijry/uview-plus/blob/be7c2f85791cdae3e0237d2b26780b2ee9a16b4f/src/uni_modules/uview-plus/components/u-form/u-form.vue#L184
=> fix(types): 修复 _FormRef 类型错误

src/uni_modules/uview-plus/components/u-action-sheet/u-action-sheet.vue
[https://github.com/ijry/uview-plus/issues/426](url)
=> 修复：ActionSheet 操作菜单cancelText属性为空DOM节点还存在并且可以点击问题

src/uni_modules/uview-plus/components/u-swiper/u-swiper.vue
=> fix:修复swiper中title换行后多余的内容未被遮挡问题

src/uni_modules/uview-plus/components/up-datetime-picker/props.js
修复up-datetime-picker组件使用的时候Property "toolbarRightSlot" was accessed during render but is not defined on instance.的提示
=> 修复up-datetime-picker组件使用的时候Property "toolbarRightSlot" was accessed during render but is not defined on instance.的提示

src/uni_modules/uview-plus/libs/function/test.js, src/uni_modules/uview-plus/libs/function/test.uts
#485 传入值为`'008'`时实际上是可以通过new Date()函数正确构造出值的，只是这种场景在开发中并不常见，大多数情况下大家觉得这应该返回错误。所以我将校验内容改为了类型+长度+正则，允许对`2020-02-10`、`2020-02-10 08:32:10`、`2020/02/10 03:10`、`2020/02/10 3:10`、`2020/02-10 3:10`及时间戳进行校验。
=> feat: 修改了libs/function下的test.js和test.uts文件中的date方法的校验为类型+正则

src/uni_modules/uview-plus/libs/function/index.js
```
// 批量注册全局组件
for (const key in importFn) {
let component = importFn[key].default;
if (component.name && component.name.indexOf('u--') !== 0) {
const name = component.name.replace(/u-([a-zA-Z0-9-_]+)/g, 'up-$1');
component.install = function (Vue) {
Vue.component(name, component);
};
// 导入组件
components.push(component);
}
}
```
`uni_modules/uview-plus/index.js`中统一将组件名称前缀替换成了up-，但是组件代码找查找父组件依然用的u前缀，比如：
`
$parent.call(instance, 'u-form-item')
`
=> 修复因为修改组件名称前缀，导致h5打包后$parent方法内找不到父组件的问题

src/uni_modules/uview-plus/components/u-picker/u-picker.vue
u-picker组件 增加当前选中item的class类名
比起使用[style*="font-weight: bold"] { }属性选择器更为方便
=> feat: 更新u-picker组件 增加当前选中class类名

src/uni_modules/uview-plus/components/u-datetime-picker/props.js, src/uni_modules/uview-plus/components/u-datetime-picker/u-datetime-picker.vue
**起因：**
up-datetime-picker不支持disabled，但是这个功能非常的场景
`<up-datetime-picker
hasInput
:show="show"
v-model="value1"
mode="datetime"
></up-datetime-picker>`
**修改：**
添加了disabled props      
**涉及修改的文件** 
/uni_modulesuview-plus/components/u-datetime-picker/props.js
/uni_modulesuview-plus/u-datetime-picker/u-datetime-picker.vue
=> up-datetime-picker日期组件支持禁用

src/uni_modules/uview-plus/components/u-search/u-search.vue
在浏览器中，u-search 组件处于禁用状态时，点击其内部的 input 无法触发 click 事件。
=> fix: u-search在h5环境下的点击失效

src/uni_modules/uview-plus/components/u-slider/u-slider.vue
**问题:**
滑块选择器（slider）在双滑块模式下，当父组件修改绑定值时，滑块选择器未正确响应，导致显示状态与绑定值不同步。
**解决方法:**
通过监听绑定值的变化，实现滑块选择器与父组件绑定值的同步更新。
=> feat: sleder滑动选择器双滑块 增加外层触发值的变动功能

src/uni_modules/uview-plus/components/u-picker/u-picker.vue
**功能描述：**
1.支持hasInput
2.有hasInput属性时候change不会修改v-model，确认时候才会
**修改内容：**
1.html模板添加了input
2.修改了watch，修复_uniApp bug_，直接父组件写defualtindex=“[1,2]”,this.$emit('update:modelValue时候会导致子组件watch defualtindex，二次触发
3.修改了方法inputLabel，返回内容改为用户确认后的内容，
4.修改了方法inputValue，区分对象数组和普通数组
=> feat:picker支持hasInput

src/uni_modules/uview-plus/components/u-upload/u-upload.vue, src/uni_modules/uview-plus/components/u-upload/utils.js
1. 'other'类型的文件缺少with/height限制;
2. 支持显示真实的文件名;
3. u-loading-icon跟白色背景重叠;
4. 优先使用文件名判断是否是图片或视频;
5. this.onAfterRead传入参数bug;
6. 组件方法chooseFile支持传入参数以覆盖组件默认属性, 供外部组件动态调用, 提高灵活性.
=> fix: u-upload

src/uni_modules/uview-plus/components/u-image/u-image.vue
给`u-image.vue`的计算属性`transStyle()`和`wrapStyle()`添加了`addUnit(this.width);`和`addUnit(this.height); `
Closes:  #701
=> fix: 修复u-image.vue在加载错误情况下高度和宽度不正确问题

src/pages/componentsC/subsection/subsection.nvue, src/uni_modules/uview-plus/components/u-subsection/props.js, src/uni_modules/uview-plus/components/u-subsection/subsection.js, src/uni_modules/uview-plus/components/u-subsection/u-subsection.vue, src/uni_modules/uview-plus/types/comps/subsection.d.ts
close #780 
activeColorKeyName 从`list`元素对象中读取激活时的颜色  如果存在字段 优先级大于 activeColor
inactiveColorKeyName 从`list`元素对象中读取未激活时的颜色 如果存在字段 优先级大于 inactiveColor
h5验证：同步更新demo
=> feat: Subsection 分段器添加支持从 list中读取激活文字颜色和未激活文字颜色

src/pages/componentsB/card/card.vue
fix: #786
这个PR是为了解决官方文档和小程序中Card示例组件多行显示省略号样式异常
效果图对比
修改前
修改后
=> fix: 官方文档和小程序中Card示例组件多行显示省略号样式异常

src/uni_modules/uview-plus/components/u-subsection/props.js
Fix #823 
`u-subsection`组件的`disabled`属性应为`Boolean`类型
=> fix: u-subsection组件的disabled属性应为Boolean类型

src/uni_modules/uview-plus/components/u-action-sheet/u-action-sheet.vue
如果给action-sheet设置了圆角（<up-action-sheet round="10" >)，且不带标题，那hover第一个列表item的时候，原本有的圆角就会消失，改了下hover style就好了
未修改之前的截图：
带圆角的列表：
带圆角列表第一个item的hover style:
修改后的效果：
=> fix: 修复action-sheet列表中第一个item的hover style

src/uni_modules/uview-plus/components/u-index-list/u-index-list.vue
微信开发工具,以及一些比较卡的手机上,无法获取到高度,增加nexttick保证获取到正确的高度
=> 🐞 fix(索引列表):解决初始化时获取不到高度导致的字母列表异常
