ijry/uview-plus

uni_modules/uview-plus/components/u-tabbar-item/u-tabbar-item.vue
=> 修复tabbar在微信小程序flex失效问题

uni_modules/uview-plus/components/u-checkbox/u-checkbox.vue
=> feat: :art: 修复 无法清空的情况

uni_modules/uview-plus/components/u-parse/parser-es-module.js, uni_modules/uview-plus/components/u-parse/u-parse.vue, uni_modules/uview-plus/components/u-skeleton/u-skeleton.vue
https://github.com/ijry/uview-plus/issues/18#issue-1377634952
https://github.com/ijry/uview-plus/issues/17#issue-1377634513
=> feat: :art: bug修复

uni_modules/uview-plus/components/u-timeline/props.js, uni_modules/uview-plus/components/u-timeline/u-drawer.vue, uni_modules/uview-plus/libs/config/props.js, uni_modules/uview-plus/libs/config/props/drawer.js
=> feat:'抽屉组件新增'

uni_modules/uview-plus/components/u-sticky/u-sticky.vue
=> u-sticky组件支持头条小程序

src/uni_modules/uview-plus/components/u-slider/u-slider.vue
=> fix(u-slider): inactiveColor can't work

src/uni_modules/uview-plus/components/u-code-input/props.js, src/uni_modules/uview-plus/components/u-code-input/u-code-input.vue
在VUE3情况下，props.js缺一个// #endif，u-code-input.vue会出现value未定义
=> 修复验证码输入组件在vue3无法输入问题

src/uni_modules/uview-plus/components/u-code/u-code.vue
if 中的timer 永远是null；
下面的逻辑不会执行。
=> 去除u-code组件setTimeToStorage函数中 !timer 的判断

src/uni_modules/uview-plus/components/u-cell/u-cell.vue, src/uni_modules/uview-plus/components/u-form-item/props.js, src/uni_modules/uview-plus/components/u-form-item/u-form-item.vue, src/uni_modules/uview-plus/components/u-form/u-form.vue, src/uni_modules/uview-plus/components/u-transition/transition.js, src/uni_modules/uview-plus/libs/config/props/formItem.js, src/uni_modules/uview-plus/libs/css/components.scss
=> feat: 增加u-form-item单独设置规则变量

src/uni_modules/uview-plus/libs/css/flex.scss
修复编译时CSS缺少分号报错：[plugin:uni:pre-css] Unbalanced delimiter found in string
=> fix:[plugin:uni:pre-css] Unbalanced delimiter found in string

src/uni_modules/uview-plus/components/u-number-box/u-number-box.vue
[dcloudio uni-app issue](https://github.com/dcloudio/uni-app/issues/3371)
#301
=> fix: 修复小程序numberbox bug

src/uni_modules/uview-plus/components/u-qrcode/u-qrcode.vue
https://github.com/ijry/uview-plus/issues/345
=> fix: 支付宝小程序二维码渲染

src/uni_modules/uview-plus/types/comps/popup.d.ts
src/uni_modules/uview-plus/components/u-popup/u-popup.vue
=> fix: upload组件参数mode添加left

src/pages/componentsC/album/album.nvue, src/uni_modules/uview-plus/components/u-album/props.js, src/uni_modules/uview-plus/components/u-album/u-album.vue, src/uni_modules/uview-plus/types/comps/album.d.ts
feat: u-album组件添加radius,shape参数，定义参考当前u-image参数
=> feat: u-album组件添加radius,shape参数，定义参考当前u-image参数

src/uni_modules/uview-plus/libs/function/index.js
=> fix: 修复 addStyle方法报错customStyle.forEach is not a function的bug

src/uni_modules/uview-plus/components/u-radio-group/u-radio-group.vue
=> u-radio-group: invalid import

src/uni_modules/uview-plus/components/u-button/vue.scss
=> Revert "边框按钮警告类型下颜色变量使用错误"

src/pages/componentsB/alert/alert.nvue, src/uni_modules/uview-plus/components/u-alert/u-alert.vue
=> feat: 在u-alert组件中添加关闭事件

src/uni_modules/uview-plus/components/u-search/u-search.vue
=> fix: u-search删除emit click时的条件编辑

src/uni_modules/uview-plus/components/u--form/u--form.vue, src/uni_modules/uview-plus/components/u-form/u-form.vue, src/uni_modules/uview-plus/components/u-picker/props.js, src/uni_modules/uview-plus/components/u-picker/u-picker.vue
=> feat:picker传递hasInput属性时候，可以禁用输入框点击

src/uni_modules/uview-plus/components/u-datetime-picker/props.js, src/uni_modules/uview-plus/components/u-datetime-picker/u-datetime-picker.vue, src/uni_modules/uview-plus/components/u-picker/props.js, src/uni_modules/uview-plus/components/u-picker/u-picker.vue
datepicker组件和picker组件 携带输入框时候，允许自定义禁用颜色
=> datepicker组件和picker组件 携带输入框时候，允许自定义禁用颜色

.vscode/settings.json, src/uni_modules/uview-plus/components/u-checkbox-group/u-checkbox-group.vue
修改u-checkbox-group组件changes事件发生位置，放在前面会出现change事件第一次没更新数据情况。
=> fix: 🐛 修改u-checkbox-group组件changes事件发生位置

src/uni_modules/uview-plus/components/u-action-sheet-data/u-action-sheet-data.vue, src/uni_modules/uview-plus/components/u-picker-data/u-picker-data.vue
✅ Closes: https://github.com/ijry/uview-plus/issues/664
=> fix: 移除mapState

src/uni_modules/uview-plus/components/u-upload/u-upload.vue, src/uni_modules/uview-plus/libs/function/test.js
=> fix: 修改 test.promise(res) 预期结果不一致

src/uni_modules/uview-plus/components/u-datetime-picker/u-datetime-picker.vue
=> fix:修改传入空字符串时导致组件崩溃

src/uni_modules/uview-plus/components/u-steps/u-steps.vue
尝试小程序使用flex布局，但是抖音小程序会出现奇奇怪怪的问题，但微信小程序表现不错
#659 
微信小程序
h5
=> fix: 修改步骤条微信小程序下的布局

src/uni_modules/uview-plus/components/u-qrcode/qrcode.js, src/uni_modules/uview-plus/components/u-qrcode/u-qrcode.vue, src/uni_modules/uview-plus/types/comps.d.ts, src/uni_modules/uview-plus/types/comps/qrcode.d.ts
=> feat: 添加qrcode长按回调添加生成图片url，修改长按事件 longpress->longpressCallback，防止编译后被干扰为根节点事件

src/uni_modules/uview-plus/components/u-qrcode/u-qrcode.vue
close: #736 
qrcode支持 新参数useRootHeightAndWidth 是否使用根节点的宽高 如果使用该参数 则size参数失效 如果根节点宽高不一致则 以短的一边为准， 需要作者更新文档
demo code
h5
微信小程序
=> * feat 二维码新增支持自适应宽高设置

src/uni_modules/uview-plus/components/u-search/u-search.vue, src/uni_modules/uview-plus/types/comps/search.d.ts
=> feat: 搜索框添加新的插槽

src/uni_modules/uview-plus/components/u-picker-data/u-picker-data.vue
fix: 解决因为层级问题导致点击picker选择器无法正常弹出
=> fix: 解决up-picker-data组件因为层级问题导致点击picker选择器无法正常弹出

src/pages/componentsC/subsection/subsection.nvue, src/uni_modules/uview-plus/components/u-subsection/props.js, src/uni_modules/uview-plus/components/u-subsection/subsection.js, src/uni_modules/uview-plus/components/u-subsection/u-subsection.vue, src/uni_modules/uview-plus/types/comps/subsection.d.ts
close: #788 
分段器添加禁用逻辑 新增参数disabled
=> feat: subsection 分段器添加禁用逻辑

src/uni_modules/uview-plus/components/u-dropdown/u-dropdown.vue
Close #794 
这个PR是为了支持u-dropdown组件的highlight方法可以同时高亮多个菜单项
highlight方法支持传入单个索引或者索引集合
=> feat: u-dropdown组件的highlight方法支持同时高亮多个菜单项

src/uni_modules/uview-plus/components/u-qrcode/u-qrcode.vue
=> 🐞 fix(u-qrcode): 解决长按事件传入错误cid导致的报错
